spring:
  application:
    name: Leaderboard-Server
  jpa:
    database:
    properties:
      hibernate.format_sql: true
      #hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://db:5432/leaderboard
    username: leaderboard
    password: leaderboard
server:
  error:
    include-stacktrace: never